### ISSUE TITLE
Add created timestamp value to listings.json

### ISSUE THREAD

**Issue by gabeklavans** [gabeklavans/you-got-listings-aggregator#4]
This will allow us to sort by most recent listing

**Comment by ggriffey** [comment]
I think we should keep track of date and time. This way, I can display dividers by date on our site, and also can have little timestamps beside the listings. (Of course, however, if we're only pulling info every hour, it might be slightly silly to label them on the hour?) Not really worth it now that I'm thinking about it. Yeah, just keep the date..

**Comment by gabeklavans** [comment]
> I think we should keep track of date and time. This way, I can display dividers by date on our site, and also can have little timestamps beside the listings. (Of course, however, if we're only pulling info every hour, it might be slightly silly to label them on the hour?) Not really worth it now that I'm thinking about it. Yeah, just keep the date..

If we use timestamps, those can be used to calculate dates. So with one integer we can have the exact second it was pulled as well as the day, for filtering/displaying

**Comment by gabeklavans** [comment]
Completed via 886f03257e08e8d6016089d44b2bfb581ec8b7be
