### ISSUE TITLE
Diagnose and fix bug 

### ISSUE THREAD

**Issue by ggriffey** [gabeklavans/you-got-listings-aggregator#5]
For some reason, sometimes the links to the listings are showing two times for one name. For example, Kieth’s will be displayed twice. Not sure whether this is a front end or backend bug

**Comment by gabeklavans** [comment]
Huh. That's super weird. Yeah I think we just keep them both. Any solution to merge these would either be convoluted or potentially obscure info.

> Maybe if one agent has the same listing twice we should include the most recent one

This would require adding timestamps to the ref links themselves which I don't think is worth it for this case.
